<?php

/**
 * CodeGenerator
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    medSoft
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CodeGenerator extends PluginCodeGenerator
{
	public function makeDefault ( $_orgID, $_orgTokenID, $_codeType )
	{
		$_flag = true;
		if($this->default_flag) {		
			$_generatedCode = CodeGeneratorTable::processDefaultSelection ( $_orgID, $_orgTokenID, $_codeType, true  );  
			if((!is_null($_generatedCode)) && $_generatedCode->id != $this->id ) {
				if($_generatedCode->code_type == $_codeType ) {
					$_generatedCode->default_flag = false;
					$_generatedCode->save();
				}		
			}		
		}
		return $_flag;
	}
	public function removeDefault()
	{
		$_flag = true;
		$this->default_flag = false;
		$this->save();

		return $_flag;
	}
	public function makeDefaultActivation($_orgID, $_orgTokenID)
	{
		$_flag = true;
		$_flag1 = true;
		$this->default_flag = true;
		$this->save();
		$_hasDefault = RequestCodeGeneratorTable::processDefaultSelection ( $_orgID, $_orgTokenID, $this->requestType, true );	
		if($_hasDefault) {
			$_flag1 = $_hasDefault->removeDefault();
		}
		
		return $_flag&&$_flag1;
	}
	// code settup adjustment function
	public function makeCodeSetup( $_codeNumber )
	{
		$_flag = true;
		$_nextCodeNumber = intval($_codeNumber)+1;
		if($this->hasDeletedCode) {					
			$_currentCode = $this->lastCode;
			$_nextCodeNumber = intval($_currentCode);
			$this->has_deleted = false;
			$this->deleted_code = null;
		}
		$this->last_code = SystemCore::processCodeInitialNumber(trim($_nextCodeNumber));
		$this->save();  
		return $_flag;
	}
	public function makeAccountCodeSetup( $_codeNumber )
	{
		$_flag = true;
		$_nextCodeNumber = intval($_codeNumber)+1;
		if($this->hasDeletedCode) {					
			$_currentCode = $this->lastCode;
			$_nextCodeNumber = intval($_currentCode);
			$this->has_deleted = false;
			$this->deleted_code = null;
		}
		$this->last_code = SystemCore::processAccountInitialNumber(trim($_nextCodeNumber));
		$this->save();  
		return $_flag;
	}
	// code settup adjustment function
	public function makeEnrollmentCodeSetup( $_codeNumber )
	{
		$_flag = true;
		$_nextCodeNumber = intval($_codeNumber)+1;
		if($this->hasDeletedCode) {					
			$_currentCode = $this->lastCode;
			$_nextCodeNumber = intval($_currentCode);
			$this->has_deleted = false;
			$this->deleted_code = null;
		}
		$this->last_code = SystemCore::processEnrollmentCodeInitialNumber(trim($_nextCodeNumber));
		$this->save();  
		return $_flag;
	}
	// code setup adjustment function
	public function makeReferenceCodeSetup ( $_codeNumber )
	{
		$_flag = true;
		$_nextCodeNumber = intval($_codeNumber)+1;
		if($this->hasDeletedCode) {					
			$_currentCode = $this->lastCode;
			$_nextCodeNumber = intval($_currentCode);
			$this->has_deleted = false;
			$this->deleted_code = null;
		}
		$this->last_code = SystemCore::makeSystemInitialCode ( $this->codeType, $_nextCodeNumber );
		$this->save();  
		return $_flag;
	}
	// code setup adjustment function
	public function makeInvoiceCodeSetup ( $_codeNumber )
	{
		$_flag = true;
		$_nextCodeNumber = intval($_codeNumber)+1;
		if($this->hasDeletedCode) {					
			$_currentCode = $this->lastCode;
			$_nextCodeNumber = intval($_currentCode);
			$this->has_deleted = false;
			$this->deleted_code = null;
		}
		$this->last_code = SystemCore::makeSystemInitialCode ( $this->codeType, $_nextCodeNumber );
		$this->save();  
		return $_flag;
	}
}
