<?php

/**
 * BaseTournamentMatchParticipantTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $token_id
 * @property integer $match_fixture_id
 * @property string $match_fixture_token_id
 * @property integer $sport_game_group_id
 * @property string $sport_game_group_token_id
 * @property integer $sport_game_team_group_id
 * @property string $effective_date
 * @property boolean $confirm_flag
 * @property boolean $active_flag
 * @property integer $approval_status
 * @property integer $status
 * @property clob $description
 * @property SportGameGroup $SportGameGroup
 * @property SportGameTeamGroup $SportGameTeamGroup
 * @property TournamentMatchFixture $TournamentMatchFixture
 * @property Doctrine_Collection $tournamentMatchParticipantTeamMemberParticipants
 * 
 * @package    mu-TMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTournamentMatchParticipantTeam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mutms_tbl_tournament_match_participant_team');
        $this->hasColumn('token_id', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('match_fixture_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('match_fixture_token_id', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('sport_game_group_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sport_game_group_token_id', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('sport_game_team_group_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('effective_date', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('confirm_flag', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('active_flag', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('approval_status', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SportGameGroup', array(
             'local' => 'sport_game_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('SportGameTeamGroup', array(
             'local' => 'sport_game_team_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('TournamentMatchFixture', array(
             'local' => 'match_fixture_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('TournamentMatchParticipant as tournamentMatchParticipantTeamMemberParticipants', array(
             'local' => 'id',
             'foreign' => 'tournament_match_participant_team_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}