<?php

/**
 * BaseTournamentMatchFixtureResult
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $token_id
 * @property integer $tournament_match_fixture_id
 * @property integer $tournament_match_fixture_group_id
 * @property integer $match_fixture_team_member_participant_id
 * @property integer $match_round_type
 * @property integer $match_result_rank
 * @property integer $match_position_order
 * @property integer $match_result_position_order
 * @property integer $match_result_point
 * @property integer $match_result_score
 * @property integer $match_result_goal_number
 * @property float $match_result_distance
 * @property float $match_result_height
 * @property datetime $match_result_time
 * @property string $effective_date
 * @property boolean $qualified_flag
 * @property boolean $active_flag
 * @property boolean $medal_award_flag
 * @property integer $qualification_status
 * @property integer $competition_status
 * @property integer $status
 * @property clob $description
 * @property TournamentMatchFixture $TournamentMatchFixture
 * @property TournamentMatchFixtureGroup $TournamentMatchFixtureGroup
 * @property TournamentMatchTeamMemberParticipant $TournamentMatchTeamMemberParticipant
 * 
 * @package    symfony
 * @subpackage model
 * @author     Mekonen Berhane
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTournamentMatchFixtureResult extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mutms_tbl_tournament_match_fixture_result');
        $this->hasColumn('token_id', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('tournament_match_fixture_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tournament_match_fixture_group_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('match_fixture_team_member_participant_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('match_round_type', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('match_result_rank', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('match_position_order', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('match_result_position_order', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('match_result_point', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('match_result_score', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('match_result_goal_number', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('match_result_distance', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('match_result_height', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('match_result_time', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('effective_date', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('qualified_flag', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('active_flag', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('medal_award_flag', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('qualification_status', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('competition_status', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TournamentMatchFixture', array(
             'local' => 'tournament_match_fixture_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('TournamentMatchFixtureGroup', array(
             'local' => 'tournament_match_fixture_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('TournamentMatchTeamMemberParticipant', array(
             'local' => 'match_fixture_team_member_participant_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}