<?php

/**
 * BaseSportGameTeamGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $token_id
 * @property integer $sport_game_group_id
 * @property integer $sport_game_group_token_id
 * @property integer $team_id
 * @property string $team_token_id
 * @property string $start_date
 * @property string $effective_date
 * @property string $end_date
 * @property boolean $active_flag
 * @property integer $status
 * @property clob $description
 * @property Team $Team
 * @property SportGameGroup $SportGameGroup
 * @property Doctrine_Collection $sportGameTeamGroupTeamMemberParticipants
 * 
 * @package    mu-TMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSportGameTeamGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mutms_tbl_sport_game_team_group');
        $this->hasColumn('token_id', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('sport_game_group_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sport_game_group_token_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('team_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('team_token_id', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('start_date', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('effective_date', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('end_date', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('active_flag', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Team', array(
             'local' => 'team_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('SportGameGroup', array(
             'local' => 'sport_game_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('GroupTeamMemberParticipant as sportGameTeamGroupTeamMemberParticipants', array(
             'local' => 'id',
             'foreign' => 'team_group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}