<?php

/**
 * PartyContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PartyContactTable extends PluginPartyContactTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PartyContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PartyContact');
    }
}