<?php

/**
 * BasePerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $personTeamParticipants
 * @property Doctrine_Collection $personUserAccounts
 * 
 * @package    symfony
 * @subpackage model
 * @author     Mekonen Berhane
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerson extends Party
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TeamMemberParticipant as personTeamParticipants', array(
             'local' => 'id',
             'foreign' => 'person_id'));

        $this->hasMany('User as personUserAccounts', array(
             'local' => 'id',
             'foreign' => 'person_id'));
    }
}