<?php

/**
 * BaseTournamentParticipantTeamMedalStanding
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $token_id
 * @property integer $org_id
 * @property string $org_token_id
 * @property integer $tournament_id
 * @property integer $team_id
 * @property string $team_token_id
 * @property integer $standing_rank
 * @property integer $gold_medal
 * @property integer $silver_medal
 * @property integer $bronze_medal
 * @property integer $total_medal_award
 * @property boolean $active_flag
 * @property integer $status
 * @property clob $description
 * @property Tournament $Tournament
 * @property Organization $Organization
 * @property Team $Team
 * 
 * @package    symfony
 * @subpackage model
 * @author     Mekonen Berhane
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTournamentParticipantTeamMedalStanding extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mutms_tbl_tournament_participant_team_medal_standing');
        $this->hasColumn('token_id', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('org_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('org_token_id', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('tournament_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('team_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('team_token_id', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('standing_rank', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('gold_medal', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('silver_medal', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('bronze_medal', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('total_medal_award', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('active_flag', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tournament', array(
             'local' => 'tournament_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Organization', array(
             'local' => 'org_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Team', array(
             'local' => 'team_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}