<?php

/**
 * UserRole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    eSIS
 * @subpackage model
 * @author     John Haftom
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserRole extends PluginUserRole
{
}
