<?php

/**
 * BaseTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $token_id
 * @property integer $org_id
 * @property integer $tournament_id
 * @property string $team_name
 * @property string $alias
 * @property string $start_date
 * @property string $end_date
 * @property boolean $active_flag
 * @property integer $status
 * @property clob $description
 * @property Organization $Organization
 * @property Tournament $Tournament
 * @property Doctrine_Collection $teamGroupMembers
 * @property Doctrine_Collection $teamParticipantPersons
 * @property Doctrine_Collection $teamsTeamDetails
 * @property Doctrine_Collection $teamMatchParticipants
 * @property Doctrine_Collection $MatchResult
 * @property Doctrine_Collection $teamMatchTables
 * @property Doctrine_Collection $teamMatchFixtureDetails
 * 
 * @package    mu-TMS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('musms_tbl_teams');
        $this->hasColumn('token_id', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('org_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tournament_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('team_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('alias', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('start_date', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('end_date', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('active_flag', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organization', array(
             'local' => 'org_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Tournament', array(
             'local' => 'tournament_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('GroupMembers as teamGroupMembers', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasMany('TeamParticipants as teamParticipantPersons', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasMany('TeamDetail as teamsTeamDetails', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasMany('MatchParticipants as teamMatchParticipants', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasMany('MatchResult', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasMany('MatchTable as teamMatchTables', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasMany('MatchFixtureDetail as teamMatchFixtureDetails', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}