<?php

/**
 * TeamDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeamDetailTable extends PluginTeamDetailTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TeamDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TeamDetail');
    }
}