<?php

/**
 * SportGameTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SportGameTable extends PluginSportGameTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SportGameTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SportGame');
    }
    //
	public static function processNew ( $_orgID, $_orgTokenID, $_gameCategoryID, $_gameCategoryTokenID, $_gameCategoryName, $_sportGameName, $_gameDistanceType, $_gameDistance, $_measurementType, $_sportGameTypeMode, $_throwTypeMode, $_jumpTypeMode, $_contestantMode, $_participantTeamMode, $_playersNumberPerGame, $_sportGameRankingMode, $_winnerTablePoint, $_drawTablePoint, $_participantNumberPerTrack, $_enableParticipantNumberPerTrackFlag, $_enablePlayerModeFlag, $_sportGameStatus, $_description, $_userID, $_userTokenID )
	{
		 $_flag = true;
				
				
			$_codeConfig = CodeGeneratorTable::processDefaultSelection (null, null, SystemCore::$_SPORT_GAME, true  ); 
			$_codeNumber =  $_codeConfig->hasDeletedCode ? $_codeConfig->deletedCode:$_codeConfig->lastCode; 
			$_sportGameNumber = $_codeConfig->prefixCode.'-'.SystemCore::processCodeGeneratorInitialNumber($_codeNumber);
			
			$_tournamentSportGameName = TournamentCore::makeTournamentSportGameName ($_contestantMode, $_playersNumberPerGame, $_gameDistance, $_measurementType, $_sportGameTypeMode, $_throwTypeMode, $_jumpTypeMode);
			$_sportGameName = ($_participantTeamMode == TournamentCore::$_PAIR_TEAM && ($_enablePlayerModeFlag)) ? (trim($_sportGameName).' '.trim(TournamentCore::makePlayerModeName($_contestantMode))):trim($_sportGameName);
			$_sportGameName = ($_participantTeamMode == TournamentCore::$_PAIR_TEAM && ($_playersNumberPerGame) && (!$_enablePlayerModeFlag)) ? (trim(intval($_playersNumberPerGame)).' X '.trim(intval($_playersNumberPerGame)).' '.trim($_sportGameName)):trim($_sportGameName);
			$_sportGameName = $_participantTeamMode == TournamentCore::$_PAIR_TEAM ? $_sportGameName:$_tournamentSportGameName;
			
			$_categoryAlias = $_categoryAlias ? SystemCore::makeAlias ( $_categoryAlias ):SystemCore::makeAlias ( $_sportGameName );
			//$_sportGameAlias = $_sportGameAlias ? SystemCore::makeAlias ( $_sportGameAlias ):SystemCore::makeAlias ( $_sportGameName );
			
			$_sportGame = self::processSave ( $_orgID, $_orgTokenID, $_gameCategoryID, $_gameCategoryName, $_sportGameName, $_sportGameAlias, $_sportGameNumber, $_gameDistanceType, $_gameDistance, $_measurementType, $_sportGameTypeMode, $_throwTypeMode, $_jumpTypeMode, $_contestantMode, $_participantTeamMode, $_playersNumberPerGame, $_sportGameRankingMode, $_winnerTablePoint, $_drawTablePoint, $_participantNumberPerTrack, $_enableParticipantNumberPerTrackFlag, $_enablePlayerModeFlag, $_sportGameStatus, $_description );
		
			$_codeConfig->makeCodeSetup ( $_codeConfig->lastCode ); 
			
			if($_orgID && $_userID) { 
				
				$_actionID = SystemCore::$_CREATE; 
				$_moduleID  = ModuleCore::$_SPORT_GAME;  
				$_actionObject  = 'Sport Game ID: '.$_sportGame->id;  
				$_actionDesc  = 'Sport Game - [ Module: '.ModuleCore::processModuleValue(ModuleCore::$_SPORT_GAME).' ]';  
			
				$_flag1 = SystemLogFileTable::processNew ($_orgID, $_orgTokenID, $_userID, $_userTokenID, $_moduleID, $_actionID, $_actionObject, $_actionDesc);
			}
		
		return $_sportGame;
	}
	//
	public static function processCreate ( )
	{
		
	} 
	public static function processSave ( $_orgID, $_orgTokenID, $_gameCategoryID, $_gameCategoryName, $_sportGameName, $_sportGameAlias, $_sportGameNumber, $_gameDistanceType, $_gameDistance, $_measurementType, $_sportGameTypeMode, $_throwTypeMode, $_jumpTypeMode, $_contestantMode, $_participantTeamMode, $_playersNumberPerGame, $_sportGameRankingMode, $_winnerTablePoint, $_drawTablePoint, $_participantNumberPerTrack, $_enableParticipantNumberPerTrackFlag, $_enablePlayerModeFlag, $_sportGameStatus, $_description )
	{
		//try {
			//if(!$_orgID || !$_name) return false;
			$_token = trim($_orgTokenID).trim($_sportGameName).trim($_sportGameAlias).trim($_gameCategoryName).rand('11111', '99999'); 
			$_startDate = date('m/d/Y', time());
			$_nw = new SportGame (); 
			$_nw->token_id = sha1(md5(trim($_token))); 
			$_nw->org_id = trim($_orgID); 
			$_nw->org_token_id = sha1(md5(trim($_orgTokenID)));  
			$_nw->sport_game_category_id = trim($_gameCategoryID); 
			$_nw->distance_type = trim($_gameDistanceType); 
			$_nw->game_distance_measurement = trim($_measurementType); 
			$_nw->game_distance = trim($_gameDistance); 
			$_nw->sport_game_number = trim($_sportGameNumber); 
			$_nw->sport_game_type_mode = trim($_sportGameTypeMode); 
			$_nw->contestant_mode = trim($_contestantMode); 
			$_nw->contestant_team_mode = trim($_participantTeamMode); 
			$_nw->team_contestants_per_game_mode = trim($_playersNumberPerGame); 
			$_nw->jump_type_mode = trim($_jumpTypeMode); 
			$_nw->throw_type_mode = trim($_throwTypeMode); 
			$_nw->win_result_table_point = trim($_winnerTablePoint); 
			$_nw->draw_result_table_point = trim($_drawTablePoint); 
			$_nw->result_ranking_mode = trim($_sportGameRankingMode); 
			$_nw->number_of_contestants_per_track_mode = trim($_participantNumberPerTrack); 
			$_nw->name = ucwords(trim($_sportGameName)); 
			$_nw->alias = trim($_sportGameAlias); 
			$_nw->start_date = trim($_startDate);  
			$_nw->enable_fixed_contestant_per_track_flag = trim($_enableParticipantNumberPerTrack);  
			$_nw->enable_player_mode_flag = trim($_enablePlayerModeFlag);  
			$_nw->active_flag = true;  
			$_nw->status = $_sportGameStatus ? $_sportGameStatus:trim(TournamentCore::$_ACTIVE);   
			$_nw->description = SystemCore::processDescription ( (trim($_gameCategoryName).' - '.trim($_sportGameName)), trim($_description) );  
			$_nw->save(); 
			
			return $_nw; 
		//} catch ( Exception $e) {
	    //  return false; 
		//}
	} 
	public static function processEdit ( )
	{
		
	} 
	//
	public static function processUpdate ( )
	{
		   
	} 
	//
	public static function processDelete( ) 
   {	
		 
	}
	//
	public static function appendPartialQueryFields ( ) 
	{		
		 
	}
	//
	public static function appendCandidateQueryFields ( ) 
	{		
		 
	}
	public static function appendQueryFields ( ) 
	{		
		 $_queryFileds = "sprtGm.id, sprtGm.name as sportGameName, sprtGm.alias as sportGameAlias, sprtGm.sport_game_number as sportGameNumber, sprtGm.sport_game_type_mode as sportGameTypeMode, sprtGm.contestant_team_mode as contestantTeamMode, sprtGm.contestant_mode as contestantMode, sprtGm.distance_type as sportGameDistanceTypeID, sprtGm.distance_type as sportGameDistanceTypeID, sprtGm.active_flag as activeFlag, sprtGm.start_date as startDate, sprtGm.effective_date as effectiveDate, sprtGm.end_date as endDate, sprtGm.created_at as createdDate,sprtGm.updated_at as updatedDate, 
		 
						gmCat.category_name as gameCategoryName, gmCat.alias as gameCategoryAlias, gmCat.category_type as gameCategoryType, gmCat.contestant_team_mode as categoryContestantTeamMode,
								
						(SELECT MAX(sprtGmGrp1.group_number) FROM TournamentSportGameGroup sprtGmGrp1 WHERE sprtGmGrp1.sport_game_id = sprtGm.id AND sprtGmGrp1.gender_category_id=".TournamentCore::$_MEN." ) as maxSportGameGroupNumberMen,
								 
						(SELECT MAX(sprtGmGrp2.group_number) FROM TournamentSportGameGroup sprtGmGrp2 WHERE sprtGmGrp2.sport_game_id = sprtGm.id AND sprtGmGrp2.gender_category_id=".TournamentCore::$_WOMEN." ) as maxSportGameGroupNumberWomen, 
						
						(SELECT MAX(sprtGmGrp3.group_number) FROM TournamentSportGameGroup sprtGmGrp3 WHERE sprtGmGrp3.sport_game_id = sprtGm.id AND sprtGmGrp3.gender_category_id=".TournamentCore::$_MIXED." ) as maxSportGameGroupNumberMixedGender, 
		";	
		return $_queryFileds;
	}
	//
  // process list selection function 
   public static function processSelection ( $_orgID=null, $_orgTokenID=null, $_categoryID=null, $_activeFlag=null, $_keyword=null, $_offset=0, $_limit=10 ) 
   {
		$_qry = Doctrine_Query::create()
				->select(self::appendQueryFields())
				->from("SportGame sprtGm") 
				->innerJoin("sprtGm.GameCategory gmCat on sprtGm.sport_game_category_id = gmCat.id ")  
				->innerJoin("sprtGm.Organization org on sprtGm.org_id = org.id ")   
				->offset($_offset)
				->limit($_limit) 
				->orderBy("sprtGm.id ASC")
				->where("sprtGm.id IS NOT NULL");
				if(!is_null($_orgID)) $_qry = $_qry->addWhere("sprtGm.org_id = ? AND sprtGm.org_token_id = ? ", array($_orgID, $_orgTokenID));
				if(!is_null($_categoryID)) $_qry = $_qry->addWhere("sprtGm.sport_game_category_id = ?", $_categoryID);    
				if(!is_null($_activeFlag)) $_qry = $_qry->addWhere("sprtGm.active_flag = ?", $_activeFlag);    
				if(!is_null($_keyword) )
					if(strcmp(trim($_keyword), "") != 0 )
						$_qry = $_qry->andWhere("sprtGm.category_name LIKE ? OR sprtGm.alias LIKE ? OR sprtGm.description LIKE ?", array( $_keyword, $_keyword, $_keyword));
				
			$_qry = $_qry->execute(array(), Doctrine_Core::HYDRATE_RECORD); 

		return ( count($_qry) <= 0 ? null:$_qry );  
	}
	//
   public static function processAll ($_orgID=null, $_orgTokenID=null, $_categoryID=null, $_activeFlag=null, $_keyword=null ) 
   {
		$_qry = Doctrine_Query::create()
				->select(self::appendQueryFields())
				->from("SportGame sprtGm") 
				->innerJoin("sprtGm.GameCategory gmCat on sprtGm.sport_game_category_id = gmCat.id ")  
				->innerJoin("sprtGm.Organization org on sprtGm.org_id = org.id ")  
				->orderBy("sprtGm.id ASC")
				->where("sprtGm.id IS NOT NULL");
				//if(!is_null($_orgID)) $_qry = $_qry->addWhere("sprtGm.org_id = ? AND sprtGm.org_token_id = ? ", array($_orgID, $_orgTokenID));
				if(!is_null($_categoryID)) $_qry = $_qry->addWhere("sprtGm.sport_game_category_id = ?", $_categoryID);    
				if(!is_null($_activeFlag)) $_qry = $_qry->addWhere("sprtGm.active_flag = ?", $_activeFlag);    
				if(!is_null($_keyword) )
					if(strcmp(trim($_keyword), "") != 0 )
						$_qry = $_qry->andWhere("sprtGm.name LIKE ? OR gmCat.category_name LIKE ? OR sprtGm.alias LIKE ? OR sprtGm.description LIKE ?", array( $_keyword, $_keyword, $_keyword, $_keyword));
				
			$_qry = $_qry->execute(array(), Doctrine_Core::HYDRATE_RECORD); 

		return ( count($_qry) <= 0 ? null:$_qry );  
	}
	//
   public static function processCandidates ( ) 
   {
		 
	}
	//
  //
	public static function processObject ( $_orgID=null, $_orgTokenID=null, $_sportGameID, $_tokenID ) 
	{
		$_qry = Doctrine_Query::create()
				->select(self::appendQueryFields())
				->from("SportGame sprtGm") 
				->innerJoin("sprtGm.GameCategory gmCat on sprtGm.sport_game_category_id = gmCat.id ")  
				->innerJoin("sprtGm.Organization org on sprtGm.org_id = org.id ")   
				->where("sprtGm.id = ? AND sprtGm.token_id = ? ", array($_sportGameID, $_tokenID ));
				if(!is_null($_orgID)) $_qry = $_qry->addWhere("sprtGm.org_id = ? AND sprtGm.org_token_id = ? ", array($_orgID, $_orgTokenID));
				$_qry = $_qry->fetchOne(array(), Doctrine_Core::HYDRATE_RECORD); 
			
		return (! $_qry ? null : $_qry ); 	
	}  
	//
   public static function makeObject ( $_orgID=null, $_matchID, $_tokenID  ) 
	{
		$_qry = Doctrine_Query::create()
				->select(self::appendQueryFields())
				->from("SportGame sprtGm") 
				->innerJoin("sprtGm.GameCategory gmCat on sprtGm.sport_game_category_id = gmCat.id ")  
				->innerJoin("sprtGm.Organization org on sprtGm.org_id = org.id ")   
				->where("gmGrp.id = ? AND gmGrp.token_id = ? ", array($_matchID, $_tokenID ));
				if(!is_null($_orgID)) $_qry = $_qry->andWhere("prt.org_id = ? AND prt.org_token_id = ?", array($_orgID, $_orgTokenID));
				$_qry = $_qry->fetchOne(array(), Doctrine_Core::HYDRATE_RECORD); 
			
		return (! $_qry ? null : $_qry ); 	
	}  
	//
   public static function makeCandidateObject ( $_orgID=null, $_activeFlag ) 
	{
		$_qry = Doctrine_Query::create()
				->select(self::appendQueryFields())
				->from("SportGame sprtGm") 
				->innerJoin("sprtGm.GameCategory gmCat on sprtGm.sport_game_category_id = gmCat.id ")  
				->innerJoin("sprtGm.Organization org on sprtGm.org_id = org.id ")   
				->where("gmGrp.id IS NOT NULL");
				//if(!is_null($_orgID)) $_qry = $_qry->andWhere("prt.org_id = ? AND prt.org_token_id = ?", array($_orgID, $_orgTokenID));
				if(!is_null($_activeFlag)) $_qry = $_qry->andWhere("gmGrp.active_flag = ?", $_activeFlag);
				$_qry = $_qry->fetchOne(array(), Doctrine_Core::HYDRATE_RECORD); 
			
		return (! $_qry ? null : $_qry ); 	
	}  
	//
	//
	public static function processCategory ( $_orgID=null, $_orgTokenID=null )
	{
		$_qry = Doctrine_Query::create()
			->select("DISTINCT(sprtGm.sport_game_category_id) AS sportGameCategoryID")
			->from("SportGame sprtGm") 
			->where("sprtGm.id IS NOT NULL AND sprtGm.active_flag IS NOT TRUE");		
				if(!is_null($_orgID)) $_qry = $_qry->addWhere("sprtGm.org_id = ? AND sprtGm.org_token_id = ? ", array($_orgID, $_orgTokenID));

			$_qry = $_qry->execute(array(), Doctrine_Core::HYDRATE_RECORD); 
		
		$_categoryID = array();
		foreach( $_qry as $_res)
			$_categoryID[] = $_res->sportGameCategoryID;
	 
		return ( count ( $_categoryID ) <= 0 ? null : $_categoryID );
	}
	
	/*********************************************************
	********** Candidate selection process *******************
	**********************************************************/
	
	// process list selection function 
   public static function makeCandidateSelections ( $_categoryID=null, $_activeFlag=null, $_keyword=null) 
   {
		$_qry = Doctrine_Query::create()
				->select(self::appendQueryFields())
				->from("SportGame sprtGm") 
				->innerJoin("sprtGm.GameCategory gmCat on sprtGm.sport_game_category_id = gmCat.id ")  
				->innerJoin("sprtGm.Organization org on sprtGm.org_id = org.id ")  
				->orderBy("sprtGm.id ASC")
				->where("sprtGm.id IS NOT NULL");
				if(!is_null($_categoryID)) $_qry = $_qry->addWhere("sprtGm.sport_game_category_id = ?", $_categoryID);    
				if(!is_null($_activeFlag)) $_qry = $_qry->addWhere("sprtGm.active_flag = ?", $_activeFlag);    
				if(!is_null($_keyword) )
					if(strcmp(trim($_keyword), "") != 0 )
						$_qry = $_qry->andWhere("sprtGm.category_name LIKE ? OR sprtGm.alias LIKE ? OR sprtGm.description LIKE ?", array( $_keyword, $_keyword, $_keyword));
				
			$_qry = $_qry->execute(array(), Doctrine_Core::HYDRATE_RECORD); 

		return ( count($_qry) <= 0 ? null:$_qry );  
	}
	//
	public static function processCandidatePersonSelection ( ) 
   { 
		
	}  
	
	/*********************************************************
	********** Candidate filtering process *******************
	**********************************************************/
	
	public static function processRoleSelection ()
	{
		 
	}
}
