<?php

/**
 * TournamentNewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TournamentNewsTable extends PluginTournamentNewsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TournamentNewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TournamentNews');
    }
}