<?php

/**
 * TournamentMatchTeamMedalAwardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TournamentMatchTeamMedalAwardTable extends PluginTournamentMatchTeamMedalAwardTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TournamentMatchTeamMedalAwardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TournamentMatchTeamMedalAward');
    }
}