<?php

/**
 * TournamentParticipantTeamMedalStandingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TournamentParticipantTeamMedalStandingTable extends PluginTournamentParticipantTeamMedalStandingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TournamentParticipantTeamMedalStandingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TournamentParticipantTeamMedalStanding');
    }
}