<?php

/**
 * TournamentMedalAwardsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TournamentMedalAwardsTable extends PluginTournamentMedalAwardsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TournamentMedalAwardsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TournamentMedalAwards');
    }
}