<?php

/**
 * PluginCompanyContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCompanyContactTable extends PartyContactTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCompanyContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCompanyContact');
    }
}