<?php

/**
 * PluginOrganizationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOrganizationTable extends PartyTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOrganizationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOrganization');
    }
}