<?php

/**
 * PluginPersonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPersonTable extends PartyTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPersonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPerson');
    }
}