<?php

/**
 * SportGameGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SportGameGroupTable extends PluginSportGameGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SportGameGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SportGameGroup');
    }
}