<?php

/**
 * PluginTournamentMedalAwardsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTournamentMedalAwardsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTournamentMedalAwardsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTournamentMedalAwards');
    }
}