<?php

/**
 * PluginGameTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginGameTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginGameTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginGame');
    }
}