<?php

/**
 * PluginTournamentRankTableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTournamentRankTableTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTournamentRankTableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTournamentRankTable');
    }
}