<?php

/**
 * PluginTournamentParticipantTeamMedalStandingDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTournamentParticipantTeamMedalStandingDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTournamentParticipantTeamMedalStandingDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTournamentParticipantTeamMedalStandingDetail');
    }
}