<?php

/**
 * PluginTeamGameParticipationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTeamGameParticipationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTeamGameParticipationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTeamGameParticipation');
    }
}