<?php

/**
 * PluginCodeGeneratorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCodeGeneratorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCodeGeneratorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCodeGenerator');
    }
}