<?php

/**
 * PluginMatchFixtureDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMatchFixtureDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMatchFixtureDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMatchFixtureDetail');
    }
}