<?php

/**
 * PluginTournamentMatchTeamMemberParticipantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTournamentMatchTeamMemberParticipantTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTournamentMatchTeamMemberParticipantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTournamentMatchTeamMemberParticipant');
    }
}