<?php

/**
 * PluginMultipleParticipantTeamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMultipleParticipantTeamTable extends TournamentMatchParticipantTeamTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMultipleParticipantTeamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMultipleParticipantTeam');
    }
}