<?php

/**
 * PluginMultipleContestantTeamGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMultipleContestantTeamGroupTable extends SportGameGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMultipleContestantTeamGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMultipleContestantTeamGroup');
    }
}