<?php

/**
 * MatchParticipantsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MatchParticipantsTable extends PluginMatchParticipantsTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MatchParticipantsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MatchParticipants');
    }
}