<?php

/**
 * MatchFixtureDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MatchFixtureDetailTable extends PluginMatchFixtureDetailTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MatchFixtureDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MatchFixtureDetail');
    }
}