<?php

/**
 * MultipleParticipantTeamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MultipleParticipantTeamTable extends PluginMultipleParticipantTeamTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MultipleParticipantTeamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MultipleParticipantTeam');
    }
}