<?php

/**
 * TeamGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeamGroupTable extends PluginTeamGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TeamGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TeamGroup');
    }
}